import "./components/pagination"
import "./components/button"
import "./components/icons/icons"
import "./components/card"
import "./components/alert"
import "./components/backdrop"
import "./components/message"
import "./components/loading"
import "./components/image-item"
import "./components/image-viewer"
import "./components/home"

import "./styles/index.css"
