import "./components/pagination"
import "./components/button"
import "./components/icons/icons"
import "./components/card"
import "./components/alert"
import "./components/backdrop"
import "./components/message"
import "./components/loading"
import "./components/home"

import "./index.css"
